
package pe.egcc.demows.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LibrosWS", targetNamespace = "http://ws.demows.egcc.pe/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LibrosWS {


    /**
     * 
     * @return
     *     returns java.util.List<pe.egcc.demows.ws.Libro>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "traerLibros", targetNamespace = "http://ws.demows.egcc.pe/", className = "pe.egcc.demows.ws.TraerLibros")
    @ResponseWrapper(localName = "traerLibrosResponse", targetNamespace = "http://ws.demows.egcc.pe/", className = "pe.egcc.demows.ws.TraerLibrosResponse")
    @Action(input = "http://ws.demows.egcc.pe/LibrosWS/traerLibrosRequest", output = "http://ws.demows.egcc.pe/LibrosWS/traerLibrosResponse")
    public List<Libro> traerLibros();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sumar", targetNamespace = "http://ws.demows.egcc.pe/", className = "pe.egcc.demows.ws.Sumar")
    @ResponseWrapper(localName = "sumarResponse", targetNamespace = "http://ws.demows.egcc.pe/", className = "pe.egcc.demows.ws.SumarResponse")
    @Action(input = "http://ws.demows.egcc.pe/LibrosWS/sumarRequest", output = "http://ws.demows.egcc.pe/LibrosWS/sumarResponse")
    public int sumar(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
