//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoNETWSClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.egcc.pe/", ConfigurationName="ServiceReference1.MateService")]
    public interface MateService {
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://ws.egcc.pe/)
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.egcc.pe/MateService/restarRequest", ReplyAction="http://ws.egcc.pe/MateService/restarResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        DemoNETWSClient.ServiceReference1.restarResponse restar(DemoNETWSClient.ServiceReference1.restarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.egcc.pe/MateService/restarRequest", ReplyAction="http://ws.egcc.pe/MateService/restarResponse")]
        System.Threading.Tasks.Task<DemoNETWSClient.ServiceReference1.restarResponse> restarAsync(DemoNETWSClient.ServiceReference1.restarRequest request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://ws.egcc.pe/)
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.egcc.pe/MateService/sumarRequest", ReplyAction="http://ws.egcc.pe/MateService/sumarResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        DemoNETWSClient.ServiceReference1.sumarResponse sumar(DemoNETWSClient.ServiceReference1.sumarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.egcc.pe/MateService/sumarRequest", ReplyAction="http://ws.egcc.pe/MateService/sumarResponse")]
        System.Threading.Tasks.Task<DemoNETWSClient.ServiceReference1.sumarResponse> sumarAsync(DemoNETWSClient.ServiceReference1.sumarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="restar", WrapperNamespace="http://ws.egcc.pe/", IsWrapped=true)]
    public partial class restarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int arg1;
        
        public restarRequest() {
        }
        
        public restarRequest(int arg0, int arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="restarResponse", WrapperNamespace="http://ws.egcc.pe/", IsWrapped=true)]
    public partial class restarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public restarResponse() {
        }
        
        public restarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sumar", WrapperNamespace="http://ws.egcc.pe/", IsWrapped=true)]
    public partial class sumarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int arg1;
        
        public sumarRequest() {
        }
        
        public sumarRequest(int arg0, int arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sumarResponse", WrapperNamespace="http://ws.egcc.pe/", IsWrapped=true)]
    public partial class sumarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public sumarResponse() {
        }
        
        public sumarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MateServiceChannel : DemoNETWSClient.ServiceReference1.MateService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MateServiceClient : System.ServiceModel.ClientBase<DemoNETWSClient.ServiceReference1.MateService>, DemoNETWSClient.ServiceReference1.MateService {
        
        public MateServiceClient() {
        }
        
        public MateServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MateServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MateServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MateServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DemoNETWSClient.ServiceReference1.restarResponse DemoNETWSClient.ServiceReference1.MateService.restar(DemoNETWSClient.ServiceReference1.restarRequest request) {
            return base.Channel.restar(request);
        }
        
        public int restar(int arg0, int arg1) {
            DemoNETWSClient.ServiceReference1.restarRequest inValue = new DemoNETWSClient.ServiceReference1.restarRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            DemoNETWSClient.ServiceReference1.restarResponse retVal = ((DemoNETWSClient.ServiceReference1.MateService)(this)).restar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DemoNETWSClient.ServiceReference1.restarResponse> DemoNETWSClient.ServiceReference1.MateService.restarAsync(DemoNETWSClient.ServiceReference1.restarRequest request) {
            return base.Channel.restarAsync(request);
        }
        
        public System.Threading.Tasks.Task<DemoNETWSClient.ServiceReference1.restarResponse> restarAsync(int arg0, int arg1) {
            DemoNETWSClient.ServiceReference1.restarRequest inValue = new DemoNETWSClient.ServiceReference1.restarRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((DemoNETWSClient.ServiceReference1.MateService)(this)).restarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DemoNETWSClient.ServiceReference1.sumarResponse DemoNETWSClient.ServiceReference1.MateService.sumar(DemoNETWSClient.ServiceReference1.sumarRequest request) {
            return base.Channel.sumar(request);
        }
        
        public int sumar(int arg0, int arg1) {
            DemoNETWSClient.ServiceReference1.sumarRequest inValue = new DemoNETWSClient.ServiceReference1.sumarRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            DemoNETWSClient.ServiceReference1.sumarResponse retVal = ((DemoNETWSClient.ServiceReference1.MateService)(this)).sumar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DemoNETWSClient.ServiceReference1.sumarResponse> DemoNETWSClient.ServiceReference1.MateService.sumarAsync(DemoNETWSClient.ServiceReference1.sumarRequest request) {
            return base.Channel.sumarAsync(request);
        }
        
        public System.Threading.Tasks.Task<DemoNETWSClient.ServiceReference1.sumarResponse> sumarAsync(int arg0, int arg1) {
            DemoNETWSClient.ServiceReference1.sumarRequest inValue = new DemoNETWSClient.ServiceReference1.sumarRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((DemoNETWSClient.ServiceReference1.MateService)(this)).sumarAsync(inValue);
        }
    }
}
