//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetMonedas.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.epmg.pe/", ConfigurationName="ServiceReference1.ConvertirWS")]
    public interface ConvertirWS {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://ws.epmg.pe/).
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.epmg.pe/ConvertirWS/euro_dolarRequest", ReplyAction="http://ws.epmg.pe/ConvertirWS/euro_dolarResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        NetMonedas.ServiceReference1.euro_dolarResponse euro_dolar(NetMonedas.ServiceReference1.euro_dolarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.epmg.pe/ConvertirWS/euro_dolarRequest", ReplyAction="http://ws.epmg.pe/ConvertirWS/euro_dolarResponse")]
        System.Threading.Tasks.Task<NetMonedas.ServiceReference1.euro_dolarResponse> euro_dolarAsync(NetMonedas.ServiceReference1.euro_dolarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://ws.epmg.pe/).
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.epmg.pe/ConvertirWS/dolar_euroRequest", ReplyAction="http://ws.epmg.pe/ConvertirWS/dolar_euroResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        NetMonedas.ServiceReference1.dolar_euroResponse dolar_euro(NetMonedas.ServiceReference1.dolar_euroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.epmg.pe/ConvertirWS/dolar_euroRequest", ReplyAction="http://ws.epmg.pe/ConvertirWS/dolar_euroResponse")]
        System.Threading.Tasks.Task<NetMonedas.ServiceReference1.dolar_euroResponse> dolar_euroAsync(NetMonedas.ServiceReference1.dolar_euroRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://ws.epmg.pe/).
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.epmg.pe/ConvertirWS/euro_solRequest", ReplyAction="http://ws.epmg.pe/ConvertirWS/euro_solResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        NetMonedas.ServiceReference1.euro_solResponse euro_sol(NetMonedas.ServiceReference1.euro_solRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.epmg.pe/ConvertirWS/euro_solRequest", ReplyAction="http://ws.epmg.pe/ConvertirWS/euro_solResponse")]
        System.Threading.Tasks.Task<NetMonedas.ServiceReference1.euro_solResponse> euro_solAsync(NetMonedas.ServiceReference1.euro_solRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://ws.epmg.pe/).
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.epmg.pe/ConvertirWS/sol_euroRequest", ReplyAction="http://ws.epmg.pe/ConvertirWS/sol_euroResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        NetMonedas.ServiceReference1.sol_euroResponse sol_euro(NetMonedas.ServiceReference1.sol_euroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.epmg.pe/ConvertirWS/sol_euroRequest", ReplyAction="http://ws.epmg.pe/ConvertirWS/sol_euroResponse")]
        System.Threading.Tasks.Task<NetMonedas.ServiceReference1.sol_euroResponse> sol_euroAsync(NetMonedas.ServiceReference1.sol_euroRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://ws.epmg.pe/).
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.epmg.pe/ConvertirWS/dolar_solRequest", ReplyAction="http://ws.epmg.pe/ConvertirWS/dolar_solResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        NetMonedas.ServiceReference1.dolar_solResponse dolar_sol(NetMonedas.ServiceReference1.dolar_solRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.epmg.pe/ConvertirWS/dolar_solRequest", ReplyAction="http://ws.epmg.pe/ConvertirWS/dolar_solResponse")]
        System.Threading.Tasks.Task<NetMonedas.ServiceReference1.dolar_solResponse> dolar_solAsync(NetMonedas.ServiceReference1.dolar_solRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://ws.epmg.pe/).
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.epmg.pe/ConvertirWS/sol_dolarRequest", ReplyAction="http://ws.epmg.pe/ConvertirWS/sol_dolarResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        NetMonedas.ServiceReference1.sol_dolarResponse sol_dolar(NetMonedas.ServiceReference1.sol_dolarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.epmg.pe/ConvertirWS/sol_dolarRequest", ReplyAction="http://ws.epmg.pe/ConvertirWS/sol_dolarResponse")]
        System.Threading.Tasks.Task<NetMonedas.ServiceReference1.sol_dolarResponse> sol_dolarAsync(NetMonedas.ServiceReference1.sol_dolarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="euro_dolar", WrapperNamespace="http://ws.epmg.pe/", IsWrapped=true)]
    public partial class euro_dolarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double monto;
        
        public euro_dolarRequest() {
        }
        
        public euro_dolarRequest(double monto) {
            this.monto = monto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="euro_dolarResponse", WrapperNamespace="http://ws.epmg.pe/", IsWrapped=true)]
    public partial class euro_dolarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public euro_dolarResponse() {
        }
        
        public euro_dolarResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="dolar_euro", WrapperNamespace="http://ws.epmg.pe/", IsWrapped=true)]
    public partial class dolar_euroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double monto;
        
        public dolar_euroRequest() {
        }
        
        public dolar_euroRequest(double monto) {
            this.monto = monto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="dolar_euroResponse", WrapperNamespace="http://ws.epmg.pe/", IsWrapped=true)]
    public partial class dolar_euroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public dolar_euroResponse() {
        }
        
        public dolar_euroResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="euro_sol", WrapperNamespace="http://ws.epmg.pe/", IsWrapped=true)]
    public partial class euro_solRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double monto;
        
        public euro_solRequest() {
        }
        
        public euro_solRequest(double monto) {
            this.monto = monto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="euro_solResponse", WrapperNamespace="http://ws.epmg.pe/", IsWrapped=true)]
    public partial class euro_solResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public euro_solResponse() {
        }
        
        public euro_solResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sol_euro", WrapperNamespace="http://ws.epmg.pe/", IsWrapped=true)]
    public partial class sol_euroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double monto;
        
        public sol_euroRequest() {
        }
        
        public sol_euroRequest(double monto) {
            this.monto = monto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sol_euroResponse", WrapperNamespace="http://ws.epmg.pe/", IsWrapped=true)]
    public partial class sol_euroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public sol_euroResponse() {
        }
        
        public sol_euroResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="dolar_sol", WrapperNamespace="http://ws.epmg.pe/", IsWrapped=true)]
    public partial class dolar_solRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double monto;
        
        public dolar_solRequest() {
        }
        
        public dolar_solRequest(double monto) {
            this.monto = monto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="dolar_solResponse", WrapperNamespace="http://ws.epmg.pe/", IsWrapped=true)]
    public partial class dolar_solResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public dolar_solResponse() {
        }
        
        public dolar_solResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sol_dolar", WrapperNamespace="http://ws.epmg.pe/", IsWrapped=true)]
    public partial class sol_dolarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double monto;
        
        public sol_dolarRequest() {
        }
        
        public sol_dolarRequest(double monto) {
            this.monto = monto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sol_dolarResponse", WrapperNamespace="http://ws.epmg.pe/", IsWrapped=true)]
    public partial class sol_dolarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public sol_dolarResponse() {
        }
        
        public sol_dolarResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConvertirWSChannel : NetMonedas.ServiceReference1.ConvertirWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConvertirWSClient : System.ServiceModel.ClientBase<NetMonedas.ServiceReference1.ConvertirWS>, NetMonedas.ServiceReference1.ConvertirWS {
        
        public ConvertirWSClient() {
        }
        
        public ConvertirWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConvertirWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConvertirWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConvertirWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NetMonedas.ServiceReference1.euro_dolarResponse NetMonedas.ServiceReference1.ConvertirWS.euro_dolar(NetMonedas.ServiceReference1.euro_dolarRequest request) {
            return base.Channel.euro_dolar(request);
        }
        
        public double euro_dolar(double monto) {
            NetMonedas.ServiceReference1.euro_dolarRequest inValue = new NetMonedas.ServiceReference1.euro_dolarRequest();
            inValue.monto = monto;
            NetMonedas.ServiceReference1.euro_dolarResponse retVal = ((NetMonedas.ServiceReference1.ConvertirWS)(this)).euro_dolar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NetMonedas.ServiceReference1.euro_dolarResponse> NetMonedas.ServiceReference1.ConvertirWS.euro_dolarAsync(NetMonedas.ServiceReference1.euro_dolarRequest request) {
            return base.Channel.euro_dolarAsync(request);
        }
        
        public System.Threading.Tasks.Task<NetMonedas.ServiceReference1.euro_dolarResponse> euro_dolarAsync(double monto) {
            NetMonedas.ServiceReference1.euro_dolarRequest inValue = new NetMonedas.ServiceReference1.euro_dolarRequest();
            inValue.monto = monto;
            return ((NetMonedas.ServiceReference1.ConvertirWS)(this)).euro_dolarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NetMonedas.ServiceReference1.dolar_euroResponse NetMonedas.ServiceReference1.ConvertirWS.dolar_euro(NetMonedas.ServiceReference1.dolar_euroRequest request) {
            return base.Channel.dolar_euro(request);
        }
        
        public double dolar_euro(double monto) {
            NetMonedas.ServiceReference1.dolar_euroRequest inValue = new NetMonedas.ServiceReference1.dolar_euroRequest();
            inValue.monto = monto;
            NetMonedas.ServiceReference1.dolar_euroResponse retVal = ((NetMonedas.ServiceReference1.ConvertirWS)(this)).dolar_euro(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NetMonedas.ServiceReference1.dolar_euroResponse> NetMonedas.ServiceReference1.ConvertirWS.dolar_euroAsync(NetMonedas.ServiceReference1.dolar_euroRequest request) {
            return base.Channel.dolar_euroAsync(request);
        }
        
        public System.Threading.Tasks.Task<NetMonedas.ServiceReference1.dolar_euroResponse> dolar_euroAsync(double monto) {
            NetMonedas.ServiceReference1.dolar_euroRequest inValue = new NetMonedas.ServiceReference1.dolar_euroRequest();
            inValue.monto = monto;
            return ((NetMonedas.ServiceReference1.ConvertirWS)(this)).dolar_euroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NetMonedas.ServiceReference1.euro_solResponse NetMonedas.ServiceReference1.ConvertirWS.euro_sol(NetMonedas.ServiceReference1.euro_solRequest request) {
            return base.Channel.euro_sol(request);
        }
        
        public double euro_sol(double monto) {
            NetMonedas.ServiceReference1.euro_solRequest inValue = new NetMonedas.ServiceReference1.euro_solRequest();
            inValue.monto = monto;
            NetMonedas.ServiceReference1.euro_solResponse retVal = ((NetMonedas.ServiceReference1.ConvertirWS)(this)).euro_sol(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NetMonedas.ServiceReference1.euro_solResponse> NetMonedas.ServiceReference1.ConvertirWS.euro_solAsync(NetMonedas.ServiceReference1.euro_solRequest request) {
            return base.Channel.euro_solAsync(request);
        }
        
        public System.Threading.Tasks.Task<NetMonedas.ServiceReference1.euro_solResponse> euro_solAsync(double monto) {
            NetMonedas.ServiceReference1.euro_solRequest inValue = new NetMonedas.ServiceReference1.euro_solRequest();
            inValue.monto = monto;
            return ((NetMonedas.ServiceReference1.ConvertirWS)(this)).euro_solAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NetMonedas.ServiceReference1.sol_euroResponse NetMonedas.ServiceReference1.ConvertirWS.sol_euro(NetMonedas.ServiceReference1.sol_euroRequest request) {
            return base.Channel.sol_euro(request);
        }
        
        public double sol_euro(double monto) {
            NetMonedas.ServiceReference1.sol_euroRequest inValue = new NetMonedas.ServiceReference1.sol_euroRequest();
            inValue.monto = monto;
            NetMonedas.ServiceReference1.sol_euroResponse retVal = ((NetMonedas.ServiceReference1.ConvertirWS)(this)).sol_euro(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NetMonedas.ServiceReference1.sol_euroResponse> NetMonedas.ServiceReference1.ConvertirWS.sol_euroAsync(NetMonedas.ServiceReference1.sol_euroRequest request) {
            return base.Channel.sol_euroAsync(request);
        }
        
        public System.Threading.Tasks.Task<NetMonedas.ServiceReference1.sol_euroResponse> sol_euroAsync(double monto) {
            NetMonedas.ServiceReference1.sol_euroRequest inValue = new NetMonedas.ServiceReference1.sol_euroRequest();
            inValue.monto = monto;
            return ((NetMonedas.ServiceReference1.ConvertirWS)(this)).sol_euroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NetMonedas.ServiceReference1.dolar_solResponse NetMonedas.ServiceReference1.ConvertirWS.dolar_sol(NetMonedas.ServiceReference1.dolar_solRequest request) {
            return base.Channel.dolar_sol(request);
        }
        
        public double dolar_sol(double monto) {
            NetMonedas.ServiceReference1.dolar_solRequest inValue = new NetMonedas.ServiceReference1.dolar_solRequest();
            inValue.monto = monto;
            NetMonedas.ServiceReference1.dolar_solResponse retVal = ((NetMonedas.ServiceReference1.ConvertirWS)(this)).dolar_sol(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NetMonedas.ServiceReference1.dolar_solResponse> NetMonedas.ServiceReference1.ConvertirWS.dolar_solAsync(NetMonedas.ServiceReference1.dolar_solRequest request) {
            return base.Channel.dolar_solAsync(request);
        }
        
        public System.Threading.Tasks.Task<NetMonedas.ServiceReference1.dolar_solResponse> dolar_solAsync(double monto) {
            NetMonedas.ServiceReference1.dolar_solRequest inValue = new NetMonedas.ServiceReference1.dolar_solRequest();
            inValue.monto = monto;
            return ((NetMonedas.ServiceReference1.ConvertirWS)(this)).dolar_solAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NetMonedas.ServiceReference1.sol_dolarResponse NetMonedas.ServiceReference1.ConvertirWS.sol_dolar(NetMonedas.ServiceReference1.sol_dolarRequest request) {
            return base.Channel.sol_dolar(request);
        }
        
        public double sol_dolar(double monto) {
            NetMonedas.ServiceReference1.sol_dolarRequest inValue = new NetMonedas.ServiceReference1.sol_dolarRequest();
            inValue.monto = monto;
            NetMonedas.ServiceReference1.sol_dolarResponse retVal = ((NetMonedas.ServiceReference1.ConvertirWS)(this)).sol_dolar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NetMonedas.ServiceReference1.sol_dolarResponse> NetMonedas.ServiceReference1.ConvertirWS.sol_dolarAsync(NetMonedas.ServiceReference1.sol_dolarRequest request) {
            return base.Channel.sol_dolarAsync(request);
        }
        
        public System.Threading.Tasks.Task<NetMonedas.ServiceReference1.sol_dolarResponse> sol_dolarAsync(double monto) {
            NetMonedas.ServiceReference1.sol_dolarRequest inValue = new NetMonedas.ServiceReference1.sol_dolarRequest();
            inValue.monto = monto;
            return ((NetMonedas.ServiceReference1.ConvertirWS)(this)).sol_dolarAsync(inValue);
        }
    }
}
