//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSCVMONEDA_CLIENT_net.CVMonedaService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.egcc.pe/", ConfigurationName="CVMonedaService.CVMonedaService")]
    public interface CVMonedaService {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://ws.egcc.pe/).
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.egcc.pe/CVMonedaService/dollarToSolRequest", ReplyAction="http://ws.egcc.pe/CVMonedaService/dollarToSolResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WSCVMONEDA_CLIENT_net.CVMonedaService.dollarToSolResponse dollarToSol(WSCVMONEDA_CLIENT_net.CVMonedaService.dollarToSolRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.egcc.pe/CVMonedaService/dollarToSolRequest", ReplyAction="http://ws.egcc.pe/CVMonedaService/dollarToSolResponse")]
        System.Threading.Tasks.Task<WSCVMONEDA_CLIENT_net.CVMonedaService.dollarToSolResponse> dollarToSolAsync(WSCVMONEDA_CLIENT_net.CVMonedaService.dollarToSolRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://ws.egcc.pe/).
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.egcc.pe/CVMonedaService/solToDollarRequest", ReplyAction="http://ws.egcc.pe/CVMonedaService/solToDollarResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WSCVMONEDA_CLIENT_net.CVMonedaService.solToDollarResponse solToDollar(WSCVMONEDA_CLIENT_net.CVMonedaService.solToDollarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.egcc.pe/CVMonedaService/solToDollarRequest", ReplyAction="http://ws.egcc.pe/CVMonedaService/solToDollarResponse")]
        System.Threading.Tasks.Task<WSCVMONEDA_CLIENT_net.CVMonedaService.solToDollarResponse> solToDollarAsync(WSCVMONEDA_CLIENT_net.CVMonedaService.solToDollarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://ws.egcc.pe/).
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.egcc.pe/CVMonedaService/euroToSolRequest", ReplyAction="http://ws.egcc.pe/CVMonedaService/euroToSolResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WSCVMONEDA_CLIENT_net.CVMonedaService.euroToSolResponse euroToSol(WSCVMONEDA_CLIENT_net.CVMonedaService.euroToSolRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.egcc.pe/CVMonedaService/euroToSolRequest", ReplyAction="http://ws.egcc.pe/CVMonedaService/euroToSolResponse")]
        System.Threading.Tasks.Task<WSCVMONEDA_CLIENT_net.CVMonedaService.euroToSolResponse> euroToSolAsync(WSCVMONEDA_CLIENT_net.CVMonedaService.euroToSolRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://ws.egcc.pe/).
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.egcc.pe/CVMonedaService/solToEuroRequest", ReplyAction="http://ws.egcc.pe/CVMonedaService/solToEuroResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WSCVMONEDA_CLIENT_net.CVMonedaService.solToEuroResponse solToEuro(WSCVMONEDA_CLIENT_net.CVMonedaService.solToEuroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.egcc.pe/CVMonedaService/solToEuroRequest", ReplyAction="http://ws.egcc.pe/CVMonedaService/solToEuroResponse")]
        System.Threading.Tasks.Task<WSCVMONEDA_CLIENT_net.CVMonedaService.solToEuroResponse> solToEuroAsync(WSCVMONEDA_CLIENT_net.CVMonedaService.solToEuroRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://ws.egcc.pe/).
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.egcc.pe/CVMonedaService/euroToDollarRequest", ReplyAction="http://ws.egcc.pe/CVMonedaService/euroToDollarResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WSCVMONEDA_CLIENT_net.CVMonedaService.euroToDollarResponse euroToDollar(WSCVMONEDA_CLIENT_net.CVMonedaService.euroToDollarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.egcc.pe/CVMonedaService/euroToDollarRequest", ReplyAction="http://ws.egcc.pe/CVMonedaService/euroToDollarResponse")]
        System.Threading.Tasks.Task<WSCVMONEDA_CLIENT_net.CVMonedaService.euroToDollarResponse> euroToDollarAsync(WSCVMONEDA_CLIENT_net.CVMonedaService.euroToDollarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://ws.egcc.pe/).
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.egcc.pe/CVMonedaService/dollarToEuroRequest", ReplyAction="http://ws.egcc.pe/CVMonedaService/dollarToEuroResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WSCVMONEDA_CLIENT_net.CVMonedaService.dollarToEuroResponse dollarToEuro(WSCVMONEDA_CLIENT_net.CVMonedaService.dollarToEuroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.egcc.pe/CVMonedaService/dollarToEuroRequest", ReplyAction="http://ws.egcc.pe/CVMonedaService/dollarToEuroResponse")]
        System.Threading.Tasks.Task<WSCVMONEDA_CLIENT_net.CVMonedaService.dollarToEuroResponse> dollarToEuroAsync(WSCVMONEDA_CLIENT_net.CVMonedaService.dollarToEuroRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="dollarToSol", WrapperNamespace="http://ws.egcc.pe/", IsWrapped=true)]
    public partial class dollarToSolRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        public dollarToSolRequest() {
        }
        
        public dollarToSolRequest(double arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="dollarToSolResponse", WrapperNamespace="http://ws.egcc.pe/", IsWrapped=true)]
    public partial class dollarToSolResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public dollarToSolResponse() {
        }
        
        public dollarToSolResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solToDollar", WrapperNamespace="http://ws.egcc.pe/", IsWrapped=true)]
    public partial class solToDollarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        public solToDollarRequest() {
        }
        
        public solToDollarRequest(double arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solToDollarResponse", WrapperNamespace="http://ws.egcc.pe/", IsWrapped=true)]
    public partial class solToDollarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public solToDollarResponse() {
        }
        
        public solToDollarResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="euroToSol", WrapperNamespace="http://ws.egcc.pe/", IsWrapped=true)]
    public partial class euroToSolRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        public euroToSolRequest() {
        }
        
        public euroToSolRequest(double arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="euroToSolResponse", WrapperNamespace="http://ws.egcc.pe/", IsWrapped=true)]
    public partial class euroToSolResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public euroToSolResponse() {
        }
        
        public euroToSolResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solToEuro", WrapperNamespace="http://ws.egcc.pe/", IsWrapped=true)]
    public partial class solToEuroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        public solToEuroRequest() {
        }
        
        public solToEuroRequest(double arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solToEuroResponse", WrapperNamespace="http://ws.egcc.pe/", IsWrapped=true)]
    public partial class solToEuroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public solToEuroResponse() {
        }
        
        public solToEuroResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="euroToDollar", WrapperNamespace="http://ws.egcc.pe/", IsWrapped=true)]
    public partial class euroToDollarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        public euroToDollarRequest() {
        }
        
        public euroToDollarRequest(double arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="euroToDollarResponse", WrapperNamespace="http://ws.egcc.pe/", IsWrapped=true)]
    public partial class euroToDollarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public euroToDollarResponse() {
        }
        
        public euroToDollarResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="dollarToEuro", WrapperNamespace="http://ws.egcc.pe/", IsWrapped=true)]
    public partial class dollarToEuroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        public dollarToEuroRequest() {
        }
        
        public dollarToEuroRequest(double arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="dollarToEuroResponse", WrapperNamespace="http://ws.egcc.pe/", IsWrapped=true)]
    public partial class dollarToEuroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public dollarToEuroResponse() {
        }
        
        public dollarToEuroResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CVMonedaServiceChannel : WSCVMONEDA_CLIENT_net.CVMonedaService.CVMonedaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CVMonedaServiceClient : System.ServiceModel.ClientBase<WSCVMONEDA_CLIENT_net.CVMonedaService.CVMonedaService>, WSCVMONEDA_CLIENT_net.CVMonedaService.CVMonedaService {
        
        public CVMonedaServiceClient() {
        }
        
        public CVMonedaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CVMonedaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CVMonedaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CVMonedaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSCVMONEDA_CLIENT_net.CVMonedaService.dollarToSolResponse WSCVMONEDA_CLIENT_net.CVMonedaService.CVMonedaService.dollarToSol(WSCVMONEDA_CLIENT_net.CVMonedaService.dollarToSolRequest request) {
            return base.Channel.dollarToSol(request);
        }
        
        public double dollarToSol(double arg0) {
            WSCVMONEDA_CLIENT_net.CVMonedaService.dollarToSolRequest inValue = new WSCVMONEDA_CLIENT_net.CVMonedaService.dollarToSolRequest();
            inValue.arg0 = arg0;
            WSCVMONEDA_CLIENT_net.CVMonedaService.dollarToSolResponse retVal = ((WSCVMONEDA_CLIENT_net.CVMonedaService.CVMonedaService)(this)).dollarToSol(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSCVMONEDA_CLIENT_net.CVMonedaService.dollarToSolResponse> WSCVMONEDA_CLIENT_net.CVMonedaService.CVMonedaService.dollarToSolAsync(WSCVMONEDA_CLIENT_net.CVMonedaService.dollarToSolRequest request) {
            return base.Channel.dollarToSolAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSCVMONEDA_CLIENT_net.CVMonedaService.dollarToSolResponse> dollarToSolAsync(double arg0) {
            WSCVMONEDA_CLIENT_net.CVMonedaService.dollarToSolRequest inValue = new WSCVMONEDA_CLIENT_net.CVMonedaService.dollarToSolRequest();
            inValue.arg0 = arg0;
            return ((WSCVMONEDA_CLIENT_net.CVMonedaService.CVMonedaService)(this)).dollarToSolAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSCVMONEDA_CLIENT_net.CVMonedaService.solToDollarResponse WSCVMONEDA_CLIENT_net.CVMonedaService.CVMonedaService.solToDollar(WSCVMONEDA_CLIENT_net.CVMonedaService.solToDollarRequest request) {
            return base.Channel.solToDollar(request);
        }
        
        public double solToDollar(double arg0) {
            WSCVMONEDA_CLIENT_net.CVMonedaService.solToDollarRequest inValue = new WSCVMONEDA_CLIENT_net.CVMonedaService.solToDollarRequest();
            inValue.arg0 = arg0;
            WSCVMONEDA_CLIENT_net.CVMonedaService.solToDollarResponse retVal = ((WSCVMONEDA_CLIENT_net.CVMonedaService.CVMonedaService)(this)).solToDollar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSCVMONEDA_CLIENT_net.CVMonedaService.solToDollarResponse> WSCVMONEDA_CLIENT_net.CVMonedaService.CVMonedaService.solToDollarAsync(WSCVMONEDA_CLIENT_net.CVMonedaService.solToDollarRequest request) {
            return base.Channel.solToDollarAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSCVMONEDA_CLIENT_net.CVMonedaService.solToDollarResponse> solToDollarAsync(double arg0) {
            WSCVMONEDA_CLIENT_net.CVMonedaService.solToDollarRequest inValue = new WSCVMONEDA_CLIENT_net.CVMonedaService.solToDollarRequest();
            inValue.arg0 = arg0;
            return ((WSCVMONEDA_CLIENT_net.CVMonedaService.CVMonedaService)(this)).solToDollarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSCVMONEDA_CLIENT_net.CVMonedaService.euroToSolResponse WSCVMONEDA_CLIENT_net.CVMonedaService.CVMonedaService.euroToSol(WSCVMONEDA_CLIENT_net.CVMonedaService.euroToSolRequest request) {
            return base.Channel.euroToSol(request);
        }
        
        public double euroToSol(double arg0) {
            WSCVMONEDA_CLIENT_net.CVMonedaService.euroToSolRequest inValue = new WSCVMONEDA_CLIENT_net.CVMonedaService.euroToSolRequest();
            inValue.arg0 = arg0;
            WSCVMONEDA_CLIENT_net.CVMonedaService.euroToSolResponse retVal = ((WSCVMONEDA_CLIENT_net.CVMonedaService.CVMonedaService)(this)).euroToSol(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSCVMONEDA_CLIENT_net.CVMonedaService.euroToSolResponse> WSCVMONEDA_CLIENT_net.CVMonedaService.CVMonedaService.euroToSolAsync(WSCVMONEDA_CLIENT_net.CVMonedaService.euroToSolRequest request) {
            return base.Channel.euroToSolAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSCVMONEDA_CLIENT_net.CVMonedaService.euroToSolResponse> euroToSolAsync(double arg0) {
            WSCVMONEDA_CLIENT_net.CVMonedaService.euroToSolRequest inValue = new WSCVMONEDA_CLIENT_net.CVMonedaService.euroToSolRequest();
            inValue.arg0 = arg0;
            return ((WSCVMONEDA_CLIENT_net.CVMonedaService.CVMonedaService)(this)).euroToSolAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSCVMONEDA_CLIENT_net.CVMonedaService.solToEuroResponse WSCVMONEDA_CLIENT_net.CVMonedaService.CVMonedaService.solToEuro(WSCVMONEDA_CLIENT_net.CVMonedaService.solToEuroRequest request) {
            return base.Channel.solToEuro(request);
        }
        
        public double solToEuro(double arg0) {
            WSCVMONEDA_CLIENT_net.CVMonedaService.solToEuroRequest inValue = new WSCVMONEDA_CLIENT_net.CVMonedaService.solToEuroRequest();
            inValue.arg0 = arg0;
            WSCVMONEDA_CLIENT_net.CVMonedaService.solToEuroResponse retVal = ((WSCVMONEDA_CLIENT_net.CVMonedaService.CVMonedaService)(this)).solToEuro(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSCVMONEDA_CLIENT_net.CVMonedaService.solToEuroResponse> WSCVMONEDA_CLIENT_net.CVMonedaService.CVMonedaService.solToEuroAsync(WSCVMONEDA_CLIENT_net.CVMonedaService.solToEuroRequest request) {
            return base.Channel.solToEuroAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSCVMONEDA_CLIENT_net.CVMonedaService.solToEuroResponse> solToEuroAsync(double arg0) {
            WSCVMONEDA_CLIENT_net.CVMonedaService.solToEuroRequest inValue = new WSCVMONEDA_CLIENT_net.CVMonedaService.solToEuroRequest();
            inValue.arg0 = arg0;
            return ((WSCVMONEDA_CLIENT_net.CVMonedaService.CVMonedaService)(this)).solToEuroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSCVMONEDA_CLIENT_net.CVMonedaService.euroToDollarResponse WSCVMONEDA_CLIENT_net.CVMonedaService.CVMonedaService.euroToDollar(WSCVMONEDA_CLIENT_net.CVMonedaService.euroToDollarRequest request) {
            return base.Channel.euroToDollar(request);
        }
        
        public double euroToDollar(double arg0) {
            WSCVMONEDA_CLIENT_net.CVMonedaService.euroToDollarRequest inValue = new WSCVMONEDA_CLIENT_net.CVMonedaService.euroToDollarRequest();
            inValue.arg0 = arg0;
            WSCVMONEDA_CLIENT_net.CVMonedaService.euroToDollarResponse retVal = ((WSCVMONEDA_CLIENT_net.CVMonedaService.CVMonedaService)(this)).euroToDollar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSCVMONEDA_CLIENT_net.CVMonedaService.euroToDollarResponse> WSCVMONEDA_CLIENT_net.CVMonedaService.CVMonedaService.euroToDollarAsync(WSCVMONEDA_CLIENT_net.CVMonedaService.euroToDollarRequest request) {
            return base.Channel.euroToDollarAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSCVMONEDA_CLIENT_net.CVMonedaService.euroToDollarResponse> euroToDollarAsync(double arg0) {
            WSCVMONEDA_CLIENT_net.CVMonedaService.euroToDollarRequest inValue = new WSCVMONEDA_CLIENT_net.CVMonedaService.euroToDollarRequest();
            inValue.arg0 = arg0;
            return ((WSCVMONEDA_CLIENT_net.CVMonedaService.CVMonedaService)(this)).euroToDollarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSCVMONEDA_CLIENT_net.CVMonedaService.dollarToEuroResponse WSCVMONEDA_CLIENT_net.CVMonedaService.CVMonedaService.dollarToEuro(WSCVMONEDA_CLIENT_net.CVMonedaService.dollarToEuroRequest request) {
            return base.Channel.dollarToEuro(request);
        }
        
        public double dollarToEuro(double arg0) {
            WSCVMONEDA_CLIENT_net.CVMonedaService.dollarToEuroRequest inValue = new WSCVMONEDA_CLIENT_net.CVMonedaService.dollarToEuroRequest();
            inValue.arg0 = arg0;
            WSCVMONEDA_CLIENT_net.CVMonedaService.dollarToEuroResponse retVal = ((WSCVMONEDA_CLIENT_net.CVMonedaService.CVMonedaService)(this)).dollarToEuro(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSCVMONEDA_CLIENT_net.CVMonedaService.dollarToEuroResponse> WSCVMONEDA_CLIENT_net.CVMonedaService.CVMonedaService.dollarToEuroAsync(WSCVMONEDA_CLIENT_net.CVMonedaService.dollarToEuroRequest request) {
            return base.Channel.dollarToEuroAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSCVMONEDA_CLIENT_net.CVMonedaService.dollarToEuroResponse> dollarToEuroAsync(double arg0) {
            WSCVMONEDA_CLIENT_net.CVMonedaService.dollarToEuroRequest inValue = new WSCVMONEDA_CLIENT_net.CVMonedaService.dollarToEuroRequest();
            inValue.arg0 = arg0;
            return ((WSCVMONEDA_CLIENT_net.CVMonedaService.CVMonedaService)(this)).dollarToEuroAsync(inValue);
        }
    }
}
